# Generated by Django 5.2.18 on 2026-10-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nsi_code",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Код АСУ НСИ"
                    ),
                ),
                (
                    "enstru_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ЕНС ТРУ"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Наименование")),
                ("unit", models.CharField(max_length=32, verbose_name="Ед. изм.")),
                (
                    "price_wo_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Маркетинговая цена за ед. без НДС, KZT",
                    ),
                ),
                ("approved_at", models.DateTimeField(verbose_name="Дата утверждения")),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=64)),
                (
                    "source_number",
                    models.CharField(
                        max_length=64, verbose_name="Номер документа-основания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Действующее"),
                ),
                (
                    "dzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.dzo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция каталога цен",
                "verbose_name_plural": "Каталог цен",
                "ordering": ["-approved_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["nsi_code", "is_active"],
                        name="pricing_pri_nsi_cod_f179d7_idx",
                    )
                ],
            },
        ),
    ]
