# Generated by Django 5.2.18 on 2026-10-07 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bin",
                    models.CharField(max_length=12, unique=True, verbose_name="БИН"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Наименование")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для запросов КП"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Пул поставщиков",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True)),
                ("items", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Отправлен"), ("answered", "Получен ответ")],
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kp_requests",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="suppliers_k_source__ab198c_idx",
                    )
                ],
            },
        ),
    ]
