# Generated by Django 5.2.18 on 2026-10-07 11:29

import apps.marketing_analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("nsi", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=32, unique=True, verbose_name="Номер"),
                ),
                (
                    "initiator_full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Инициатор (ФИО)"
                    ),
                ),
                (
                    "initiator_position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность инициатора"
                    ),
                ),
                (
                    "initiator_department",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Подразделение инициатора",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("collecting_kp", "Сбор КП"),
                            ("on_approval_dzo", "На согласовании (ДЗО)"),
                            ("on_approval_db", "На согласовании ДБ КМГ"),
                            ("on_final_approval", "На утверждении директора ДБ КМГ"),
                            ("rework", "На доработке"),
                            ("approved", "Утверждено"),
                            ("cancelled", "Аннулировано"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "current_stage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Согласующие ДЗО"),
                            (2, "Департамент бюджетирования КМГ"),
                            (3, "Директор департамента бюджетирования КМГ"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "iteration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Итерация маршрута (счётчик отправок)"
                    ),
                ),
                (
                    "returned_from_stage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Согласующие ДЗО"),
                            (2, "Департамент бюджетирования КМГ"),
                            (3, "Директор департамента бюджетирования КМГ"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "price_justification",
                    models.TextField(blank=True, verbose_name="Обоснование цены"),
                ),
                (
                    "total_wo_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Итоговая сумма без НДС, KZT",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="marketing_analysis/conclusions/"
                    ),
                ),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "pdf_status",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("pending", "Формируется"),
                            ("ready", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Маркетолог",
                    ),
                ),
                (
                    "dzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.dzo",
                        verbose_name="ДЗО",
                    ),
                ),
                (
                    "initiator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Маркетинговый анализ",
                "verbose_name_plural": "Маркетинговые анализы",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommercialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=500, verbose_name="Поставщик"),
                ),
                ("supplier_bin", models.CharField(max_length=12, verbose_name="БИН")),
                ("offer_date", models.DateField(verbose_name="Дата КП")),
                (
                    "currency",
                    models.CharField(
                        default="KZT", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="Курс НБ РК на дату КП",
                    ),
                ),
                (
                    "vat_included",
                    models.BooleanField(default=False, verbose_name="Цены с НДС"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.marketing_analysis.models.upload_offer_to
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Загружено маркетологом"),
                            ("system", "Получено через систему"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kp_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="suppliers.kprequest",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="marketing_analysis.marketinganalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteration", models.PositiveIntegerField()),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Согласующие ДЗО"),
                            (2, "Департамент бюджетирования КМГ"),
                            (3, "Директор департамента бюджетирования КМГ"),
                        ]
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("assignee_role", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидает очереди"),
                            ("pending", "На рассмотрении"),
                            ("approved", "Согласовано"),
                            ("returned", "Возвращено на доработку"),
                            ("skipped", "Не рассматривалось"),
                        ],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("decided_by_name", models.CharField(blank=True, max_length=255)),
                ("decided_by_position", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="marketing_analysis.marketinganalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["iteration", "stage", "order"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisApprover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvers",
                        to="marketing_analysis.marketinganalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MarketingAnalysisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField()),
                (
                    "nsi_code",
                    models.CharField(max_length=32, verbose_name="Код АСУ НСИ"),
                ),
                (
                    "enstru_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ЕНС ТРУ"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Наименование")),
                (
                    "characteristics",
                    models.TextField(blank=True, verbose_name="Краткая характеристика"),
                ),
                ("unit", models.CharField(max_length=32, verbose_name="Ед. изм.")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="Количество"
                    ),
                ),
                (
                    "delivery_place",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Место поставки"
                    ),
                ),
                (
                    "delivery_term",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Срок поставки"
                    ),
                ),
                (
                    "marketing_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Маркетинговая цена за ед. без НДС, KZT",
                    ),
                ),
                (
                    "total_wo_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Сумма без НДС, KZT",
                    ),
                ),
                ("calc_method", models.CharField(blank=True, max_length=16)),
                (
                    "price_justification",
                    models.TextField(
                        blank=True, verbose_name="Обоснование цены по позиции"
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketing_analysis.marketinganalysis",
                    ),
                ),
                (
                    "nsi_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="nsi.nsiproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItemAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.marketing_analysis.models.upload_attachment_to
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="marketing_analysis.marketinganalysisitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommercialOfferPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Цена за ед. в валюте КП",
                    ),
                ),
                (
                    "price_kzt_wo_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Цена за ед. KZT без НДС",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="marketing_analysis.commercialoffer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_prices",
                        to="marketing_analysis.marketinganalysisitem",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="marketinganalysis",
            index=models.Index(fields=["status"], name="marketing_a_status_bf50b2_idx"),
        ),
        migrations.AddIndex(
            model_name="marketinganalysis",
            index=models.Index(
                fields=["dzo", "status"], name="marketing_a_dzo_id_1500a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketinganalysis",
            index=models.Index(
                fields=["author"], name="marketing_a_author__a6688c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["status", "assignee_user"], name="marketing_a_status_3b0051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["status", "assignee_role"], name="marketing_a_status_095a55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["analysis", "iteration"], name="marketing_a_analysi_902e55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisapprover",
            constraint=models.UniqueConstraint(
                fields=("analysis", "user"), name="uniq_ma_approver"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketinganalysisitem",
            constraint=models.UniqueConstraint(
                fields=("analysis", "line_no"), name="uniq_ma_item_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialofferprice",
            constraint=models.UniqueConstraint(
                fields=("offer", "item"), name="uniq_offer_item_price"
            ),
        ),
    ]
