# Generated by Django 5.2.18 on 2026-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NsiProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nsi_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Код АСУ НСИ"
                    ),
                ),
                (
                    "enstru_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ЕНС ТРУ"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Наименование")),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Краткая характеристика"),
                ),
                (
                    "unit",
                    models.CharField(max_length=32, verbose_name="Единица измерения"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Товар АСУ НСИ",
                "verbose_name_plural": "Товары АСУ НСИ",
                "ordering": ["nsi_code"],
            },
        ),
    ]
